=== arkort/CSIT341/Шехмаметьев/Task3/Task3/ValidateFigures.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ValidateFigures"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:simpleType name="positiveFloat">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0"></xs:minInclusive>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="positiveFloatWithoutZero">
    <xs:restriction base="xs:float">
      <xs:minExclusive value="0"></xs:minExclusive>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="color">
    <xs:restriction base="xs:token">
      <xs:pattern value="0x[\dA-F]{6}([\dA-F][\dA-F])?"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="Point">
    <xs:attribute name="X" type="positiveFloat"></xs:attribute>
    <xs:attribute name="Y" type="positiveFloat"></xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="Line">
    <xs:sequence>
      <xs:element name="start" type="Point"></xs:element>
      <xs:element name="end" type="Point"></xs:element>
    </xs:sequence>
    <xs:attribute name="color" type="color"></xs:attribute>
    <xs:attribute name="penWidth" type="positiveFloatWithoutZero"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="Rectangle">
    <xs:sequence>
      <xs:element name="upperLeft" type="Point"></xs:element>
    </xs:sequence>
    <xs:attribute name="height" type="positiveFloatWithoutZero"></xs:attribute>
    <xs:attribute name="width" type="positiveFloatWithoutZero"></xs:attribute>
    <xs:attribute name="color" type="color"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="Circle">
    <xs:sequence>
      <xs:element name="center" type="Point"></xs:element>
    </xs:sequence>
    <xs:attribute name="radius" type="positiveFloatWithoutZero"></xs:attribute>
    <xs:attribute name="color" type="color"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="Triangle">
    <xs:sequence>
      <xs:element name="lowerLeft" type="Point"></xs:element>
      <xs:element name="top" type="Point"></xs:element>
      <xs:element name="lowerRight" type="Point"></xs:element>
    </xs:sequence>
    <xs:attribute name="color" type="color"></xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="Figures">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="Line" type="Line"></xs:element>
      <xs:element name="Rectangle" type="Rectangle"></xs:element>
      <xs:element name="Circle" type="Circle"></xs:element>
      <xs:element name="Triangle" type="Triangle"></xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:element name="Figures" type="Figures"></xs:element>
</xs:schema>

=== arkort/CSIT341/Шехмаметьев/Task3/Task3/Figures2.xml
<?xml version="1.0" encoding="utf-8" ?>
<Figures
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ValidateFigures.xsd" >
  
    <Rectangle color="0xFFFF0000" height="100" width="100">
      <upperLeft X="100" Y="100"/>
    </Rectangle>

  <Circle color="0xFFFFFF00" radius="50">
    <center X="150" Y="150"/>
  </Circle>

  <Triangle color="0xFF000000">
    <lowerLeft X="110" Y="180"/>
    <top X="150" Y="100"/>
    <lowerRight X="190" Y="180"/>
  </Triangle>
</Figures>

=== arkort/CSIT341/Шехмаметьев/Task3/Task3/Figures.xml
<?xml version="1.0" encoding="utf-8" ?>
<Figures  
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ValidateFigures.xsd" >

  <Rectangle color="0xFF0000FF" height="200" width="200">
    <upperLeft X="500" Y="500"/>
  </Rectangle>

  <Triangle color ="0xFFFF0000">
    <lowerLeft X="500" Y="500"/>
    <top X="600" Y="300"/>
    <lowerRight X="700" Y="500"/>
  </Triangle>

  <Circle color="0xFFFFFF00" radius="40">
    <center X="600" Y="425"/>
  </Circle>

  <Line color="0xFFFFFFFF" penWidth="5">
    <start X="560" Y="425"/>
    <end X="640" Y="425"/>
  </Line>

  <Line color="0xFFFFFFFF" penWidth="5">
    <start X="600" Y="465"/>
    <end X="600" Y="385"/>
  </Line>

  <Rectangle color="0xFFA0522D" height="100" width="50">
    <upperLeft X="600" Y="600"/>
  </Rectangle>

  <Circle color="0xFFFFFFFF" radius="5">
    <center X="610" Y="650"/>
  </Circle>

  <Rectangle color="0xFFA0522D" height="100" width="50">
    <upperLeft X="550" Y="600"/>
  </Rectangle>

  <Circle color="0xFFFFFFFF" radius="5">
    <center X="590" Y="650"/>
  </Circle>

  <Line color="0xFF000000" penWidth="2">
    <start X="600" Y="600"/>
    <end X="600" Y="700"/>
  </Line>
  
</Figures>
